// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FunctionalKey: typeof import('./src/components/FunctionalKey.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputContext: typeof import('./src/components/InputContext.vue')['default']
    KeyBoard: typeof import('./src/components/KeyBoard.vue')['default']
    KeyBoardKey: typeof import('./src/components/KeyBoardKey.vue')['default']
    KeyRow: typeof import('./src/components/KeyRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShiftKey: typeof import('./src/components/ShiftKey.vue')['default']
  }
}

export {}
